# NumPy Fundamentals

### Mounting Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [3]:
content_path = '/content/gdrive/MyDrive/Learning/complete_data_analyst_course/exercises/S23 - Numpy Fundamentals/'

### 1. Run the following cells:

In [4]:
import numpy as np

In [5]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [6]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [7]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Display the first element (not necessarily individual element) for each of the 3 arrays we defined above.

In [8]:
array_1D[0]

10

In [25]:
array_2D[0]

array([20, 30, 40, 50, 60])

In [26]:
array_3D[0]

array([[ 1,  2,  3,  4,  5],
       [11, 21, 31, 41, 51]])

### 3. Call the first individual element of the each of the 3 arrays. 

In [27]:
array_1D[0]

10

In [28]:
array_2D[0,0]

20

In [29]:
array_3D[0,0,0]

1

### 4. Uses negative indices to display the last element of each array.

In [30]:
array_1D[-1]

14

In [33]:
array_2D[-1,-1]

55

In [34]:
array_3D[-1,-1,-1]

5

### 5. Set the penultimate (second-to-last) <i> individual </i> element of each array equal to 10. Then display the variables to check your work. 
(<b>Hint</b>: If it's the penultimate individual element of the 2-D/3-D array, it needs to be in the last row of the 2-D array)

In [35]:
array_1D[-2] = 10
array_1D

array([10, 11, 12, 10, 14])

In [36]:
array_2D[-1,-2] = 10
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 10, 55]])

In [37]:
array_3D[-1,-1,-2] = 10
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 10,  5]]])

### 6. Set the last column of the 2-D array to 100. Then display the variables to check your work. 

In [40]:
array_2D[:,-1] = 100
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  10, 100]])

### 7. Set all the values of the 3-D array to 1000. Then display the variables to check your work. 

In [41]:
array_3D[:] = 1000
array_3D

array([[[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]],

       [[1000, 1000, 1000, 1000, 1000],
        [1000, 1000, 1000, 1000, 1000]]])

### 8. Run the next 3 cells to re-define the 3 arrays, since we altered their contents. 

In [42]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [43]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [44]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 9. Add 2 to every element of the 3 arrays without overwriting their values.

In [45]:
array_1D + 2

array([12, 13, 14, 15, 16])

In [46]:
array_2D + 2

array([[22, 32, 42, 52, 62],
       [45, 56, 67, 78, 89],
       [13, 24, 35, 46, 57]])

In [47]:
array_3D + 2

array([[[ 3,  4,  5,  6,  7],
        [13, 23, 33, 43, 53]],

       [[13, 14, 15, 16, 17],
        [53, 54, 55, 56,  7]]])

### 10. Multiply the values of each array by 100 without overwriting their values.

In [48]:
array_1D * 100

array([1000, 1100, 1200, 1300, 1400])

In [49]:
array_2D * 100

array([[2000, 3000, 4000, 5000, 6000],
       [4300, 5400, 6500, 7600, 8700],
       [1100, 2200, 3300, 4400, 5500]])

In [50]:
array_3D * 100

array([[[ 100,  200,  300,  400,  500],
        [1100, 2100, 3100, 4100, 5100]],

       [[1100, 1200, 1300, 1400, 1500],
        [5100, 5200, 5300, 5400,  500]]])

### 11. Add up <i>array_1D</i> and the first row of <i>array_2D</i>

In [51]:
array_1D + array_2D[0]

array([30, 41, 52, 63, 74])

### 12. Find the product of <i>array_1D</i> and the first row of <i>array_2D</i>

In [52]:
array_1D * array_2D[0]

array([200, 330, 480, 650, 840])

### 13. Find the product  of the first row of <i>array_2D</i> and the first row of the first array of <i> array_3D </i>

In [55]:
array_2D * array_3D[0][0]

array([[ 20,  60, 120, 200, 300],
       [ 43, 108, 195, 304, 435],
       [ 11,  44,  99, 176, 275]])

### 14. Subtract <i> array_1D </i> from the first row of <i>array_2D</i>

In [56]:
array_1D - array_2D[0]

array([-10, -19, -28, -37, -46])

### 15. Subtract the first row of <i>array_2D</i> from  <i> array_1D </i> 

In [57]:
array_2D[0] - array_1D

array([10, 19, 28, 37, 46])

### 16. Alter the code in the next 3 cells to re-define the 3 arrays as the following datatypes:
    A) array_1D -> NumPy Strings
    B) array_2D -> Complex Numbers
    C) array_3D -> 64-bit Floats
    
   (<b>Hint</b>: The datatypes are the following: <i>np.str</i>, <i>np.complex</i>, <i>np.float64</i>)

In [58]:
array_1D = np.array([10,11,12,13,14], dtype=str)
array_1D

array(['10', '11', '12', '13', '14'], dtype='<U2')

In [61]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype=complex)
array_2D

array([[20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j, 60.+0.j],
       [43.+0.j, 54.+0.j, 65.+0.j, 76.+0.j, 87.+0.j],
       [11.+0.j, 22.+0.j, 33.+0.j, 44.+0.j, 55.+0.j]])

In [62]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype=np.float64)
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]])

### 17. Now run the next 3 cells to re-define the 3 arrays as 32-bit floats, since we want to run some more computations on them

In [63]:
array_1D = np.array([10,11,12,13,14], dtype = np.float32)
array_1D

array([10., 11., 12., 13., 14.], dtype=float32)

In [64]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]], dtype = np.float32)
array_2D

array([[20., 30., 40., 50., 60.],
       [43., 54., 65., 76., 87.],
       [11., 22., 33., 44., 55.]], dtype=float32)

In [65]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]], dtype = np.float32)
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]], dtype=float32)

### 18. Use broadcasting to subtract  <i>array_1D</i> from every row of <i> array_2D </i> 
   (<b>Hint</b>: You **don't** need a function to do this.)

In [66]:
array_1D - array_2D

array([[-10., -19., -28., -37., -46.],
       [-33., -43., -53., -63., -73.],
       [ -1., -11., -21., -31., -41.]], dtype=float32)

### 19. Use broadcasting to divide all rows of <i>array_3D</i> by <i> array_1D </i> 

In [67]:
array_3D / array_1D

array([[[0.1       , 0.18181819, 0.25      , 0.30769232, 0.35714287],
        [1.1       , 1.9090909 , 2.5833333 , 3.1538463 , 3.642857  ]],

       [[1.1       , 1.0909091 , 1.0833334 , 1.0769231 , 1.0714285 ],
        [5.1       , 4.7272725 , 4.4166665 , 4.1538463 , 0.35714287]]],
      dtype=float32)

### 19. Use broadcasting to find the product of all rows of <i>array_3D</i>  and the last row of <i> array_2D </i> 

In [68]:
array_3D * array_2D[-1]

array([[[  11.,   44.,   99.,  176.,  275.],
        [ 121.,  462., 1023., 1804., 2805.]],

       [[ 121.,  264.,  429.,  616.,  825.],
        [ 561., 1144., 1749., 2376.,  275.]]], dtype=float32)

### 20. Since these products are all integers, let's cast them as such
   (<b>Hint</b>: You can use the np.array() function here)

In [70]:
np.array(array_3D * array_2D[-1], dtype=int)

array([[[  11,   44,   99,  176,  275],
        [ 121,  462, 1023, 1804, 2805]],

       [[ 121,  264,  429,  616,  825],
        [ 561, 1144, 1749, 2376,  275]]])

### 21. Let's use axis argument of the np.mean() function to find the mean for every column of the 2-D array

In [73]:
np.mean(array_2D, axis=0)

array([24.666666, 35.333332, 46.      , 56.666668, 67.333336],
      dtype=float32)

### 22. Let's use axis argument of the np.mean() function to find the mean for every column of the 3-D array
   (<b>Hint</b>: Make sure you define the correct axis.)

In [75]:
np.mean(array_3D, axis=1)

array([[ 6. , 11.5, 17. , 22.5, 28. ],
       [31. , 32. , 33. , 34. , 10. ]], dtype=float32)