In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
# Defining path
content_path = '/content/gdrive/MyDrive/Learning/complete_data_analyst_course/exercises'
data_dir = content_path+'/datasets'

# NumPy DataTypes

In [ ]:
import numpy as np

### 1. With the help of the <i> np.array() </i>function, create a 1-D array variable <i> array_hw_1 </i> with the numbers from 1 to 8 and display it on the screen.

In [ ]:
array_hw_1 = np.array([list(range(1,9))])
array_hw_1

array([[1, 2, 3, 4, 5, 6, 7, 8]])

### 2.Check its type, shape and size. 
<i> (<b>Hint </b>: "type" is a Python function, while "shape" and "size" are attributes of the array) </i>

In [ ]:
type(array_hw_1)

numpy.ndarray

In [ ]:
array_hw_1.shape

(1, 8)

In [ ]:
array_hw_1.size

8

### 3. Now, create a 2x4 2-D array, <i> array_hw_2</i> with the same values & display it on screen. 

In [ ]:
array_hw_2 = np.array([[1,2,3,4],[5,6,7,8]])
array_hw_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 4. Find its type, shape, and size. 

In [ ]:
type(array_hw_2)

numpy.ndarray

In [ ]:
array_hw_2.shape

(2, 4)

In [ ]:
array_hw_2.size

8

### 5. Use square brackets to create a 3-D array with the same values as <i> array_hw_3 </i> and display it on screen.

In [ ]:
array_hw_3 = np.array([[[1,2,3,4],[5,6,7,8]]])
array_hw_3

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

### 6. Find its type, shape and size. 


In [ ]:
type(array_hw_3)

numpy.ndarray

In [ ]:
array_hw_3.shape

(1, 2, 4)

In [ ]:
array_hw_3.size

8

### 7. Define a 2-D list <i> list_hw_1 </i> with the same values as <i> array_hw_2 </i>and display it on screen.

In [ ]:
list_hw_1 = [[1,2,3,4],[5,6,7,8]]
list_hw_1

[[1, 2, 3, 4], [5, 6, 7, 8]]

### 8. Find the length of this 2-D list. 

In [ ]:
len(list_hw_1)

2

### 9. Find the length of one of its sublists. 

In [ ]:
len(list_hw_1[0])

4

### 10. Verify its type. 

In [ ]:
type(list_hw_1)

list

### 11. Use the <i>np.array()</i> function to create an array out of <i> list_hw_1</i> and display it on screen.

In [ ]:
array_hw_4 = np.array(list_hw_1)

In [ ]:
array_hw_4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 12. Create two more variables and display them on screen:
    A) A list which is the sum of the two sublists of list_hw_1;
    B) An array which is the sum of the two subarrays of array_hw_4;
    
    (Hint: Use indexing to refer to the different sub-lists/arrays)

In [ ]:
list_sum_hw_1 = list_hw_1[0] + list_hw_1[1]

In [ ]:
list_sum_hw_1

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
array_sum_hw_4 = array_hw_4[0] + array_hw_4[1]

In [ ]:
array_sum_hw_4

array([ 6,  8, 10, 12])

### 13. Find the square roots of all the elements in <i> array_sum </i>
   <i> (<b>Hint</b>: Use the np.sqrt() function)

In [ ]:
np.sqrt(array_sum_hw_4)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

### 13. Find the square roots of all the elements in <i> list_sum </i>
   <i> (<b>Hint</b>: Most NumPy functions are equipped to handle <b> lists </b>like ndarrays with the same shape)

In [ ]:
np.sqrt(list_sum_hw_1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

### 14. Use <i> np.genfromtxt() </i> to import the <i> "Lending-Company-Total-Price.csv" </i> file as strings and display its contents.
    You can open the file in a text editor like Notepad++ to check its delimiter. 

In [ ]:
lending_co_TP = np.genfromtxt(data_dir+"/Lending-Company-Total-Price.csv", delimiter=",", dtype=np.str_)
lending_co_TP

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2', '16600'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600'],
       ...,
       ['413', 'id_413', 'Product B', ..., 'Location 135', 'Region 1',
        '16600'],
       ['414', 'id_414', 'Product C', ..., 'Location 200', 'Region 6',
        '15600'],
       ['415', 'id_415', 'Product A', ..., 'Location 8', 'Region 2',
        '22250']], dtype='<U14')

### 15. Use the <i> skip_header </i> and <i> usecols </i> parameters to only take the numerical data from the file. Then, let's see how the inputs change if we alter the datatype argument to:

    A) The default (not specify it)
    B) 32-bit integers (np.int32)
    C) 32-bit floats (np.float32)
    D) 64-bit complex numbers (np.complex64)
    E) Unicode (np.unicode)
    F) Objects (np.object)
    G) None

In [ ]:
lending_co_TP_num = np.genfromtxt(data_dir+"/Lending-Company-Total-Price.csv",
                              delimiter = ',',
                              skip_header = 1, 
                              usecols = (0,-1),
                              #                       
                              # dtype = np.int32,     
                              # dtype = np.float32,   
                              # dtype = np.complex64, 
                              # dtype = np.unicode,   
                              # dtype = np.objects,   
                              # dype = None           
                             )
lending_co_TP_num

array([[1.0000e+00, 1.6600e+04],
       [2.0000e+00, 1.6600e+04],
       [3.0000e+00, 1.5600e+04],
       [4.0000e+00, 1.6600e+04],
       [5.0000e+00, 2.0250e+04],
       [6.0000e+00,        nan],
       [7.0000e+00, 2.0250e+04],
       [8.0000e+00, 1.6600e+04],
       [9.0000e+00, 2.2250e+04],
       [1.0000e+01, 2.0250e+04],
       [1.1000e+01, 1.6600e+04],
       [1.2000e+01, 2.0250e+04],
       [1.3000e+01, 1.6600e+04],
       [1.4000e+01, 2.0750e+04],
       [1.5000e+01, 2.2250e+04],
       [1.6000e+01, 1.6600e+04],
       [1.7000e+01, 2.2250e+04],
       [1.8000e+01, 1.6600e+04],
       [1.9000e+01, 1.6600e+04],
       [2.0000e+01, 5.4625e+04],
       [2.1000e+01, 1.6600e+04],
       [2.2000e+01, 2.2250e+04],
       [2.3000e+01, 1.9250e+04],
       [2.4000e+01, 1.5600e+04],
       [2.5000e+01, 2.0250e+04],
       [2.6000e+01, 2.2250e+04],
       [2.7000e+01, 1.9250e+04],
       [2.8000e+01, 6.9225e+04],
       [2.9000e+01, 2.0250e+04],
       [3.0000e+01, 1.6600e+04],
       [3.

### 16. Setting the datatype to None means the function automatically chooses the datatype for each column of the text file, so let's see how this works for all the columns.

In [ ]:
lending_co_TP_none = np.genfromtxt(data_dir+"/Lending-Company-Total-Price.csv",
                                  delimiter=",",
                                  skip_header = 1,
                                  dtype=None)

lending_co_TP_none

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([(  1, b'id_1', b'Product B', b'Male', b'Location 2', b'Region 2', 16600),
       (  2, b'id_2', b'Product B', b'Male', b'Location 3', b'', 16600),
       (  3, b'id_3', b'Product C', b'Female', b'Location 5', b'Region 5', 15600),
       (  4, b'id_4', b'Product B', b'Male', b'Location 6', b'Region 1', 16600),
       (  5, b'id_5', b'Product D', b'Female', b'Location 7', b'Region 2', 20250),
       (  6, b'id_6', b'Product B', b'Female', b'Location 10', b'Region 2',    -1),
       (  7, b'id_7', b'Product A', b'Male', b'Location 11', b'Region 3', 20250),
       (  8, b'id_8', b'Product B', b'Male', b'Location 12', b'Region 6', 16600),
       (  9, b'id_9', b'Product A', b'Female', b'Location 3', b'Region 3', 22250),
       ( 10, b'id_10', b'Product A', b'Female', b'Location 13', b'Region 6', 20250),
       ( 11, b'id_11', b'Product B', b'Female', b'Location 15', b'Region 2', 16600),
       ( 12, b'id_12', b'Product D', b'Female', b'Location 16', b'Region 1', 20250),
       ( 13, 